name: Deploy Theme to WordPress

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Sync Files to Hosting
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: '195.88.211.70'
          username: 'TemaWordpress@gamemodia.com'
          password: 'asep12345@@@'
          server-dir: /
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            README*.txt
